# Generated by Django 6.0.6 on 2026-06-26 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisKPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jenis', models.CharField(max_length=100)),
                ('tipe', models.CharField(choices=[('subsidi', 'KPR Subsidi'), ('komersil', 'KPR Komersil')], max_length=20)),
                ('bunga_per_tahun', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenor_maksimal_tahun', models.IntegerField()),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jenis KPR',
                'verbose_name_plural': 'Jenis KPR',
            },
        ),
        migrations.CreateModel(
            name='PengajuanKPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemohon', models.CharField(max_length=200)),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telepon', models.CharField(max_length=20)),
                ('harga_properti', models.DecimalField(decimal_places=2, max_digits=15)),
                ('uang_muka', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tenor_tahun', models.IntegerField()),
                ('penghasilan_bulanan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('diproses', 'Diproses'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
                ('tanggal_pengajuan', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_kpr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pengajuan', to='properti.jeniskpr')),
            ],
            options={
                'verbose_name': 'Pengajuan KPR',
                'verbose_name_plural': 'Pengajuan KPR',
            },
        ),
        migrations.CreateModel(
            name='CicilanDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan_ke', models.IntegerField()),
                ('tanggal_jatuh_tempo', models.DateField()),
                ('jumlah_cicilan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status_bayar', models.BooleanField(default=False)),
                ('tanggal_bayar', models.DateField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cicilan_developer', to='properti.pengajuankpr')),
            ],
            options={
                'verbose_name': 'Cicilan Developer',
                'verbose_name_plural': 'Cicilan Developer',
                'ordering': ['bulan_ke'],
            },
        ),
        migrations.CreateModel(
            name='Cicilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan_ke', models.IntegerField()),
                ('tanggal_jatuh_tempo', models.DateField()),
                ('jumlah_cicilan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pokok', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bunga', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status_bayar', models.BooleanField(default=False)),
                ('tanggal_bayar', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cicilan', to='properti.pengajuankpr')),
            ],
            options={
                'verbose_name': 'Cicilan',
                'verbose_name_plural': 'Cicilan',
                'ordering': ['bulan_ke'],
            },
        ),
    ]
